#%RAML 1.0 DataType

additionalProperties: false
properties:
  meta:
    properties:
      status:
        enum: [ success, failed ]
      messages:
        type: array
        items: !include ResponseMessage.raml