#%RAML 1.0 NamedExample

meta:
  status: "success"
  messages:
    -
      code: "info"
      description: "Solicitud procesada"
      level: "info"
data:
  users:
  -
    username: "adan.gomez"
    id: "1"
    name: "adan gomez"